
title: Фондация "Защото ни е грижа"
email: sunshine_171@abv.bg
description: >- # this means to ignore newlines until "baseurl:"
     Фондация, основана на доброта, хуманност и грижа!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rdimitrova
github_username:  renetadimitrova96

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
